### ISSUE TITLE
Clone到本地后,python install所需库之后,运行不起来?

### ISSUE THREAD

**Issue by wuhongnpm** [liwanlei/jiekou-python3#15]
你好.Clone到本地后,python install所需库之后,python run_excel_re.py提示错误?
D:\workapp\python3\python.exe D:/jiekou-python3/run_excel_re.py
[2020-05-09 17:45:42.707797] INFO: jiekou: 当前模块 requests封装
[2020-05-09 17:45:42.708766] INFO: jiekou: 全部args参数参数信息 , ()
[2020-05-09 17:45:42.708766] INFO: jiekou: 全部kwargs参数信息 , {}
[2020-05-09 17:45:42.710759] INFO: jiekou: 当前模块 解析测试用例文件
[2020-05-09 17:45:42.710759] INFO: jiekou: 全部args参数参数信息 , ('D:\\jiekou-python3\\test_case_data\\case.xlsx',)
[2020-05-09 17:45:42.710759] INFO: jiekou: 全部kwargs参数信息 , {}
[2020-05-09 17:45:42.731704] INFO: jiekou: 当前模块 解析测试用例文件
[2020-05-09 17:45:42.732701] INFO: jiekou: 全部args参数参数信息 , ()
[2020-05-09 17:45:42.732701] INFO: jiekou: 全部kwargs参数信息 , {}
Traceback (most recent call last):
  File "D:/jiekou-python3/run_excel_re.py", line 32, in <module>
    teThread()
  File "D:/jiekou-python3/run_excel_re.py", line 29, in teThread
    m.run()
  File "D:\workapp\python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/jiekou-python3/run_excel_re.py", line 17, in start
    listid,listkey,listconeent,listurl,listfangshi,listqiwang,listname=datacel()
  File "D:\jiekou-python3\Public\log.py", line 34, in _wrap
    return function(*args, **kwargs)
TypeError: datacel() missing 1 required positional argument: 'filrpath'

**Comment by wuhongnpm** [comment]
是什么问题呢,我该怎么做?

**Comment by liwanlei** [comment]
缺少一个路径，/run_excel_re.py", line 17, in start
listid,listkey,listconeent,listurl,listfangshi,listqiwang,listname=datacel()

Datacel没有传文件路径。




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2020年05月09日 17:46，SoapEye 写道：

是什么问题呢,我该怎么做?
