### ISSUE TITLE
python run_new.py缺少makedata

### ISSUE THREAD

**Issue by shenbh** [liwanlei/jiekou-python3#16]
python run_new.py
[2020-06-23 17:35:29.135490] INFO: jiekou: 当前模块 requests封装
[2020-06-23 17:35:29.136489] INFO: jiekou: 全部args参数参数信息 , ()
[2020-06-23 17:35:29.136489] INFO: jiekou: 全部kwargs参数信息 , {}
Traceback (most recent call last):
  File "run_new.py", line 3, in <module>
    from testCase.ddt_case import MyTest
  File "E:\py_demo\jiekou-python3-master\testCase\ddt_case.py", line 2, in <module>
    from Public.get_excel import datacel, makedata
ImportError: cannot import name 'makedata' from 'Public.get_excel' (E:\py_demo\jiekou-python3-master\Public\get_excel.py)

**Comment by liwanlei** [comment]
新版本 还是这样吗  新版本已经优化了这个问题了。
