### ISSUE TITLE
运行run_dubbo_html.py出现的问题

### ISSUE THREAD

**Issue by 1014TaoTao** [liwanlei/jiekou-python3#17]
这个问题怎么解决？有朋友遇到吗？
Traceback (most recent call last):
  File "F:/pycharm_project/API/jiekou-python3-master/run_dubbo_html.py", line 31, in <module>
    start_dubbo_case()
  File "F:/pycharm_project/API/jiekou-python3-master/run_dubbo_html.py", line 16, in start_dubbo_case
    listrelust, list_fail, list_pass, list_json, list_exption, list_weizhi = testdubbointerface()
TypeError: cannot unpack non-iterable NoneType object

**Comment by liwanlei** [comment]
这个问题是类型不对吧

**Comment by joanna1111111** [comment]
刚遇到，还不知道怎么解决，请问你解决了么

**Comment by liwanlei** [comment]
是不是没有读到数据，新版本已经不支持了，
