### ISSUE TITLE
运行run_html.py出现的问题

### ISSUE THREAD

**Issue by 1014TaoTao** [liwanlei/jiekou-python3#18]
这个问题有朋友遇到吗？怎么解决
Traceback (most recent call last):
  File "F:/pycharm_project/API/jiekou-python3-master/run_html.py", line 38, in <module>
    tThread()
  File "F:/pycharm_project/API/jiekou-python3-master/run_html.py", line 34, in tThread
    m.run()
  File "D:\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:/pycharm_project/API/jiekou-python3-master/run_html.py", line 19, in stast
    listrelust, list_fail, list_pass, list_json = testinterface()
ValueError: too many values to unpack (expected 4)

**Comment by liwanlei** [comment]
看着报错是参数和接受的长短不一样
