### ISSUE TITLE
运行run_http_html.py出现的问题

### ISSUE THREAD

**Issue by 1014TaoTao** [liwanlei/jiekou-python3#19]
'touch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "F:/pycharm_project/API/jiekou-python3-master/run_http_html.py", line 33, in <module>
    start_interface_html_http()
  File "F:/pycharm_project/API/jiekou-python3-master/run_http_html.py", line 29, in start_interface_html_http
    send_ding(content=contec)
  File "F:\pycharm_project\API\jiekou-python3-master\Public\Dingtalk.py", line 18, in send_ding
    f = requests.post(url, data=json.dumps(pagrem), headers=headers)
  File "D:\python\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "D:\python\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "D:\python\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "D:\python\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by liwanlei** [comment]
这个是因为钉钉机器人的原因，我已经标注 不用可以注释对应的代码即可
