### ISSUE TITLE
运行run.new.py出现的问题

### ISSUE THREAD

**Issue by 1014TaoTao** [liwanlei/jiekou-python3#20]
Traceback (most recent call last):
  File "F:/pycharm_project/API/jiekou-python3-master/run_new.py", line 3, in <module>
    from testCase.ddt_case import MyTest
  File "F:\pycharm_project\API\jiekou-python3-master\testCase\ddt_case.py", line 9, in <module>
    data_test = makedata()
  File "F:\pycharm_project\API\jiekou-python3-master\Public\log.py", line 40, in _wrap
    return function(*args, **kwargs)
TypeError: makedata() missing 1 required positional argument: 'filrpath'

**Comment by liwanlei** [comment]
没有传递参数啊，新的版本已经维护进去了
